version: 2
jobs:
  test:
    docker: [ { image: 'circleci/openjdk:11-node' } ]
    steps:
      - checkout
      - run:
          name: Audit extension dependencies
          command: |
            cd extension && yarn audit --level medium
      - run:
          name: Run extension test suite
          command: |
            cd extension && yarn install && yarn run jest
            
workflows:
  version: 2
  build_deploy:
    jobs:
      - test:
          filters: { tags: { only: /.*/ } }
