version: 2
jobs:
  test:
    docker: [ { image: 'circleci/openjdk:11-node' } ]
    steps:
      - checkout
      - run:
          name: Audit extension dependencies
          command: |
            cd extension && yarn audit --level medium
      - run:
          name: Run extension test suite
          command: |
            cd extension && yarn install && yarn run jest
            
  circle-all:
    docker:
    - image: busybox:1.34.1
    resource_class: small
    steps:
    - run:
        command: echo "All required jobs finished successfully"
workflows:
  version: 2
  build_deploy:
    jobs:
      - test:
          filters: { tags: { only: /.*/ } }
      - circle-all:
          requires:
          - test
          filters:
            tags:
              only: /.*/
